name: Build Speedhack (32-bit)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build DLL
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3

      # Install Toolchain Rust (Stable)
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-i686-pc-windows-msvc # WAJIB VERSI 32-BIT (i686)

      # Cache agar build selanjutnya lebih cepat
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      # Proses Build
      - name: Build Version.dll
        shell: powershell
        run: |
          # Set Environment Variable agar build script tahu kita mau hijack siapa
          $env:PROXY_DLL = "version.dll"
          
          # Build Release untuk target 32-bit
          cargo build --release --target i686-pc-windows-msvc

      # Mengumpulkan file hasil build
      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path "artifacts"
          # Copy DLL hasil compile
          Copy-Item "target/i686-pc-windows-msvc/release/version.dll" -Destination "artifacts/version.dll"

      # Upload hasil agar bisa didownload user
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Speedhack-Rust-32bit
          path: artifacts/version.dll
